package NeuroshimaHexDB.dao;

import NeuroshimaHexDB.dao.mappers.ResultSetMapper;
import NeuroshimaHexDB.dao.uow.UnitOfWork;
import NeuroshimaHexDB.domain.Borgo;

import java.sql.Connection;
import java.sql.SQLException;

public class BorgoRepository extends SuperiorRepository<Borgo> {

    public BorgoRepository(Connection connection, ResultSetMapper<Borgo> mapper, UnitOfWork uow) throws SQLException {
       super(connection, mapper, uow);
    }

    @Override
    protected String insertSql() {
        return "INSERT INTO BORGO (unit_name, initiative, attributes) VALUES (?, ?, ?)";
    }

    @Override
    protected String updateSql() {
        return "UPDATE borgo SET (unit_name, initiative, attributes) = (?, ?, ?) WHERE id = ?";
    }

    @Override
    protected String deleteSql() {
        return "DELETE FROM borgo WHERE id = ?";
    }

    @Override
    protected String selectAllSql() {
        return "SELECT * FROM borgo";
    }

    @Override
    protected String tableName() {
        return "borgo";
    }

    @Override
    protected String createTableSql() {
        return "CREATE TABLE borgo ("
                + "id INT GENERATED BY DEFAULT AS IDENTITY,"
                + "unit_name VARCHAR(30),"
                + "initiative INT(1),"
                + "attributes VARCHAR(50)"
                + ")";
    }

//    @Override
//    public void createTable() {
//        super.createTable();
//    }

    @Override
    protected void setupInsert(Borgo borgo) throws SQLException {
        insert.setString(1, borgo.getUnit_name());
        insert.setInt(2, borgo.getInitiative());
        insert.setString(3, borgo.getAttributes());
    }

    @Override
    protected void setUpdate(Borgo borgo) throws SQLException {
        update.setString(1, borgo.getUnit_name());
        update.setInt(2, borgo.getInitiative());
        update.setString(3, borgo.getAttributes());
        update.setInt(4, borgo.getId());
    }
}
