package NeuroshimaHexDB.dao;

import NeuroshimaHexDB.dao.mappers.ResultSetMapper;
import NeuroshimaHexDB.dao.uow.UnitOfWork;
import NeuroshimaHexDB.domain.Hegemonia;

import java.sql.Connection;
import java.sql.SQLException;

public class HegemoniaRepository extends SuperiorRepository<Hegemonia> {

    public HegemoniaRepository(Connection connection, ResultSetMapper<Hegemonia> mapper, UnitOfWork uow) throws SQLException {
        super(connection, mapper, uow);
    }

    @Override
    protected String insertSql() {
        return "INSERT INTO hegemonia (unit_name, initiative, primary_main_damage, attributes) VALUES (?, ?, ?, ?)";
    }

    @Override
    protected String updateSql() {
        return "UPDATE hegemonia SET (unit_name, initiative, primary_main_damage, attributes) = (?, ?, ?, ?) WHERE id = ?";
    }

    @Override
    protected String deleteSql() {
        return "DELETE FROM hegemonia WHERE id = ?";
    }

    @Override
    protected String selectAllSql() {
        return "SELECT * FROM hegemonia";
    }

    @Override
    protected String tableName() {
        return "hegemonia";
    }

    @Override
    protected String createTableSql() {
        return "CREATE TABLE hegemonia ("
                + "id INT GENERATED BY DEFAULT AS IDENTITY,"
                + "unit_name VARCHAR(30),"
                + "initiative INT(1),"
                + "primary_main_damage INT(1),"
                + "attributes VARCHAR(50)"
                + ")";
    }

    @Override
    public void createTable() {
        super.createTable();
    }

    @Override
    protected void setupInsert(Hegemonia hegemonia) throws SQLException {
        insert.setString(1, hegemonia.getUnit_name());
        insert.setInt(2, hegemonia.getInitiative());
        insert.setInt(3, hegemonia.getPrimary_main_damage());
        insert.setString(4, hegemonia.getAttributes());
    }

    @Override
    protected void setUpdate(Hegemonia hegemonia) throws SQLException {
        update.setString(1, hegemonia.getUnit_name());
        update.setInt(2, hegemonia.getInitiative());
        update.setInt(3, hegemonia.getPrimary_main_damage());
        update.setString(4, hegemonia.getAttributes());
        update.setInt(5, hegemonia.getId());
    }
}
